version: "3.7"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: especializati/laravel9-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel-9

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - "8989:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - laravel-9

    # db mysql
    db:
        container_name: mysql
        image: mysql:5.7.31
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports: 
            - '3306:3306'

    # queue
    queue:
        image: especializati/laravel9-app
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - app
        networks:
            - laravel-9

    # redis
    redis:
        image: redis:latest
        networks:
            - laravel-9

    jenkins:
        image: jenkinsci/blueocean
        ports:
        - '8084:8080'
        volumes:
        - 'jenkins_home:/var/jenkins_home'
        - '/var/run/docker.sock:/var/run/docker.sock'

    sonarqube:
        image: sonarqube:community
        hostname: sonarqube
        container_name: sonarqube
        ports:
            - "9000:9000"
        volumes:
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_extensions:/opt/sonarqube/extensions
            - sonarqube_logs:/opt/sonarqube/logs
           
volumes:
    jenkins_home:
        driver: local
    sonarqube_data:
    sonarqube_extensions:
    sonarqube_logs:
   
networks:
    laravel-9:
        driver: bridge

